#!/usr/bin/env node
/**
 * inject-config.js — bake build-time secrets into the app WITHOUT committing
 * them to source control.
 *
 * Runs automatically before every build via the npm build scripts. It writes
 * src/main/config.generated.js (gitignored) from environment variables so the
 * GitHub feedback token can be embedded in a packaged build while never
 * appearing in the repo or its git history.
 *
 * Usage (normally invoked by `npm run build`, but safe to run directly):
 *   GH_ISSUES_TOKEN=github_pat_... node scripts/inject-config.js
 */
'use strict';

const fs = require('fs');
const path = require('path');

const token = process.env.GH_ISSUES_TOKEN || '';
const repo = process.env.GH_ISSUES_REPO || 'PrimeUpYourLife/1132-Fixer-Windows';

const outDir = path.join(__dirname, '..', 'src', 'main');
const outFile = path.join(outDir, 'config.generated.js');

const body =
  '// AUTO-GENERATED by scripts/inject-config.js at build time. DO NOT COMMIT.\n' +
  '// Regenerated on every build from the GH_ISSUES_TOKEN / GH_ISSUES_REPO env vars.\n' +
  'module.exports = ' + JSON.stringify({ GH_ISSUES_TOKEN: token, GH_ISSUES_REPO: repo }, null, 2) + ';\n';

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(outFile, body);

if (token) {
  console.log(`[inject-config] wrote ${path.relative(process.cwd(), outFile)} (token present, repo=${repo})`);
} else {
  console.warn('[inject-config] GH_ISSUES_TOKEN not set — building WITHOUT a feedback token.');
  console.warn('[inject-config] In-app feedback will report "Feedback service not configured" in this build.');
}
