#!/usr/bin/env node
/**
 * inject-config.js — bake build-time configuration into the app.
 *
 * NOTE: this no longer injects any secret, and must never be used to.
 * The GitHub token now lives server-side in feedback-proxy/; the app only
 * needs the proxy's PUBLIC url. Anything written here ends up inside app.asar
 * in the shipped installer, where it is trivially readable — so only
 * non-sensitive values belong in this file's output.
 *
 * Writes src/main/config.generated.js (gitignored) from:
 *   FEEDBACK_PROXY_URL   e.g. https://feedback.example.com
 *
 * Usage (normally invoked by `npm run build`):
 *   FEEDBACK_PROXY_URL=https://... node scripts/inject-config.js
 */
'use strict';

const fs = require('fs');
const path = require('path');

const url = (process.env.FEEDBACK_PROXY_URL || '').trim();

const outDir = path.join(__dirname, '..', 'src', 'main');
const outFile = path.join(outDir, 'config.generated.js');

// Guard: a token must never reach the client bundle again.
if (/^gh[pous]_|^github_pat_/.test(url)) {
  console.error('[inject-config] FATAL: FEEDBACK_PROXY_URL looks like a GitHub token.');
  console.error('[inject-config] Secrets must NOT be bundled into the app — the token belongs');
  console.error('[inject-config] in the feedback-proxy service, not in the client. Aborting.');
  process.exit(1);
}

if (url && !/^https:\/\//i.test(url) && !/^http:\/\/(localhost|127\.0\.0\.1)/i.test(url)) {
  console.error(`[inject-config] FATAL: FEEDBACK_PROXY_URL must be https (got: ${url}). Aborting.`);
  process.exit(1);
}

const body =
  '// AUTO-GENERATED by scripts/inject-config.js at build time. DO NOT COMMIT.\n' +
  '// Contains NO secrets — only the public feedback proxy endpoint.\n' +
  'module.exports = ' + JSON.stringify({ FEEDBACK_PROXY_URL: url }, null, 2) + ';\n';

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(outFile, body);

if (url) {
  console.log(`[inject-config] wrote ${path.relative(process.cwd(), outFile)} (proxy=${url})`);
} else {
  console.warn('[inject-config] FEEDBACK_PROXY_URL not set — building WITHOUT in-app feedback.');
  console.warn('[inject-config] The app will report "Feedback service not configured". This is safe.');
}
